### ISSUE TITLE
Z-Radio crashing the game due to Rendering Screen error

### ISSUE THREAD

**Issue by LavaHoleD** [ZeEvoker2Vex/Z-Radio-Addon#3]
Sometimes when opening the GUI the game crashes.
[crash-2022-05-28_15.11.45-client.txt](https://github.com/ZeEvoker2Vex/Z-Radio-Addon/files/8791175/crash-2022-05-28_15.11.45-client.txt)
Not sure what is causing it.

**Comment by ZeEvoker2Vex** [comment]
Hey!
Does the bug occur every time you try to open the GUI?

**Comment by LavaHoleD** [comment]
> Hey! Does the bug occur every time you try to open the GUI?

Not really, sometimes it does, for me it only happened twice and then never again. Perhaps because I don't really use the radio that frequently.

**Comment by ZeEvoker2Vex** [comment]
Okay, thanks for the report, I will fix it as soon as I can ^^

**Comment by SeedenDev** [comment]
You can download the latest version of the mod, the issue is fixed :)
Thanks for your report!
